INSERT INTO `BACKGROUNDIMAGE` (`BACKGROUNDIMAGE_ID`, `WIDTH`, `HEIGHT`, `IMAGEURL`, `IMAGEDESC`, `STATUS`) VALUES (1, 271, 134, 'background/gxzdhdd.jpg', NULL, '1');
INSERT INTO `BACKGROUNDIMAGE` (`BACKGROUNDIMAGE_ID`, `WIDTH`, `HEIGHT`, `IMAGEURL`, `IMAGEDESC`, `STATUS`) VALUES (2, 271, 134, 'background/gxzdhdd.jpg', NULL, '1');
INSERT INTO `BACKGROUNDIMAGE` (`BACKGROUNDIMAGE_ID`, `WIDTH`, `HEIGHT`, `IMAGEURL`, `IMAGEDESC`, `STATUS`) VALUES (3, 271, 134, 'background/gxzdhdd.jpg', NULL, '1');
INSERT INTO `BACKGROUNDIMAGE` (`BACKGROUNDIMAGE_ID`, `WIDTH`, `HEIGHT`, `IMAGEURL`, `IMAGEDESC`, `STATUS`) VALUES (4, 271, 134, 'background/gxzdhdd.jpg', NULL, '1');
INSERT INTO `BACKGROUNDIMAGE` (`BACKGROUNDIMAGE_ID`, `WIDTH`, `HEIGHT`, `IMAGEURL`, `IMAGEDESC`, `STATUS`) VALUES (5, 271, 134, 'background/gxzdhdd.jpg', NULL, '1');
INSERT INTO `BACKGROUNDIMAGE` (`BACKGROUNDIMAGE_ID`, `WIDTH`, `HEIGHT`, `IMAGEURL`, `IMAGEDESC`, `STATUS`) VALUES (6, 271, 134, 'background/gxzdhdd.jpg', NULL, '1');
