INSERT INTO `LEAVE_MESSAGE_RECORD` (`LEAVE_MESSAGE__RECORD_ID`, `MEMBER_ID`, `IMAGE_ID`, `MESSAGE`, `LEAVE_MESSAGE_DATE`, `STATUS`) VALUES (1, 1, 1, 'aaaa', '2014-5-27 20:42:35', '1');
INSERT INTO `LEAVE_MESSAGE_RECORD` (`LEAVE_MESSAGE__RECORD_ID`, `MEMBER_ID`, `IMAGE_ID`, `MESSAGE`, `LEAVE_MESSAGE_DATE`, `STATUS`) VALUES (2, 2, 1, 'bbbb', '2014-5-27 20:42:21', '1');
INSERT INTO `LEAVE_MESSAGE_RECORD` (`LEAVE_MESSAGE__RECORD_ID`, `MEMBER_ID`, `IMAGE_ID`, `MESSAGE`, `LEAVE_MESSAGE_DATE`, `STATUS`) VALUES (3, 3, 1, 'cccc', '2014-5-27 20:42:31', '1');
INSERT INTO `LEAVE_MESSAGE_RECORD` (`LEAVE_MESSAGE__RECORD_ID`, `MEMBER_ID`, `IMAGE_ID`, `MESSAGE`, `LEAVE_MESSAGE_DATE`, `STATUS`) VALUES (4, 4, 1, 'dddd', '2014-5-27 20:42:45', '1');
INSERT INTO `LEAVE_MESSAGE_RECORD` (`LEAVE_MESSAGE__RECORD_ID`, `MEMBER_ID`, `IMAGE_ID`, `MESSAGE`, `LEAVE_MESSAGE_DATE`, `STATUS`) VALUES (5, 1, 2, 'abc', '2014-5-27 20:43:01', '1');
INSERT INTO `LEAVE_MESSAGE_RECORD` (`LEAVE_MESSAGE__RECORD_ID`, `MEMBER_ID`, `IMAGE_ID`, `MESSAGE`, `LEAVE_MESSAGE_DATE`, `STATUS`) VALUES (6, 2, 2, 'qwe', '2014-5-27 20:43:10', '1');
INSERT INTO `LEAVE_MESSAGE_RECORD` (`LEAVE_MESSAGE__RECORD_ID`, `MEMBER_ID`, `IMAGE_ID`, `MESSAGE`, `LEAVE_MESSAGE_DATE`, `STATUS`) VALUES (7, 3, 2, 'oip', '2014-5-27 20:43:22', '1');
