INSERT INTO `MEM_PROFILE` (`MEMBER_ID`, `PORTRAIT_URL`, `PROFESSION`, `BLOOD_TYPE`) VALUES (1, 'test1', NULL, NULL);
INSERT INTO `MEM_PROFILE` (`MEMBER_ID`, `PORTRAIT_URL`, `PROFESSION`, `BLOOD_TYPE`) VALUES (2, 'test2', NULL, NULL);
INSERT INTO `MEM_PROFILE` (`MEMBER_ID`, `PORTRAIT_URL`, `PROFESSION`, `BLOOD_TYPE`) VALUES (3, 'test3', NULL, NULL);
INSERT INTO `MEM_PROFILE` (`MEMBER_ID`, `PORTRAIT_URL`, `PROFESSION`, `BLOOD_TYPE`) VALUES (4, 'test4', NULL, NULL);
