INSERT INTO `MEM_ACCOUNT` (`MEMBER_ID`, `BALANCE`, `VOTES`) VALUES (1, 0, 2);
INSERT INTO `MEM_ACCOUNT` (`MEMBER_ID`, `BALANCE`, `VOTES`) VALUES (2, 0, 4);
INSERT INTO `MEM_ACCOUNT` (`MEMBER_ID`, `BALANCE`, `VOTES`) VALUES (3, 0, 1);
