INSERT INTO `STRONG_PUSH` (`MEMBER_ID`, `MEMBER_MEMBER_ID`, `STATUS`, `PUSH_LEVEL`, `CREATE_DATE`, `UPDATE_DATE`) VALUES (1, 2, '0', '0', '2014-5-23 17:52:07', '2014-5-23 17:52:10');
INSERT INTO `STRONG_PUSH` (`MEMBER_ID`, `MEMBER_MEMBER_ID`, `STATUS`, `PUSH_LEVEL`, `CREATE_DATE`, `UPDATE_DATE`) VALUES (1, 3, '0', '1', NULL, NULL);
INSERT INTO `STRONG_PUSH` (`MEMBER_ID`, `MEMBER_MEMBER_ID`, `STATUS`, `PUSH_LEVEL`, `CREATE_DATE`, `UPDATE_DATE`) VALUES (1, 4, '0', '2', NULL, NULL);
INSERT INTO `STRONG_PUSH` (`MEMBER_ID`, `MEMBER_MEMBER_ID`, `STATUS`, `PUSH_LEVEL`, `CREATE_DATE`, `UPDATE_DATE`) VALUES (1, 5, '0', '3', NULL, NULL);
INSERT INTO `STRONG_PUSH` (`MEMBER_ID`, `MEMBER_MEMBER_ID`, `STATUS`, `PUSH_LEVEL`, `CREATE_DATE`, `UPDATE_DATE`) VALUES (1, 6, '0', '3', NULL, NULL);
INSERT INTO `STRONG_PUSH` (`MEMBER_ID`, `MEMBER_MEMBER_ID`, `STATUS`, `PUSH_LEVEL`, `CREATE_DATE`, `UPDATE_DATE`) VALUES (2, 1, '0', '0', NULL, NULL);
INSERT INTO `STRONG_PUSH` (`MEMBER_ID`, `MEMBER_MEMBER_ID`, `STATUS`, `PUSH_LEVEL`, `CREATE_DATE`, `UPDATE_DATE`) VALUES (2, 3, '0', '1', NULL, NULL);
INSERT INTO `STRONG_PUSH` (`MEMBER_ID`, `MEMBER_MEMBER_ID`, `STATUS`, `PUSH_LEVEL`, `CREATE_DATE`, `UPDATE_DATE`) VALUES (2, 4, '0', '2', NULL, NULL);
